version: "3"

services:
  db:
    image: "postgres:13-alpine"
    env_file:
      - ./api.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - test_network

  api:
    build: ./
    image: ggndp/model_deploy_pipe:v1
    env_file:
      - ./api.env
    command:  uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
